# YAML configuration file schema
cluster:
  type: dict
  schema:
    id:
      type: string
      allowed:
        - leonhardmed
    host:
      type: string
      required: False
    batch_jobs:
      type: list
      schema:
        type: string
    tunnels:
      type: list
      required: False
      schema:
        type: string
    setup:
      type: boolean
      default: False

batch_jobs:
  type: dict
  valuesrules:
    type: dict
    schema:
      screen:
        type: string
        required: False
      duration:
        type: integer
        required: False
        default: 24
      cpu:
        type: integer
        required: False
        default: 1
      memory:
        type: integer
        required: False
        default: 10
      gpu:
        type: integer
        required: False
        default: 0
      gpu_model:
        type: string
        required: False
        default: GeForceGTX1080Ti
      env:
        type: list
        required: False
        schema:
          type: string
      run:
        type: list
        required: False
        schema:
          type: string
      singularity:
        type: dict
        required: False
        schema:
          image:
            type: string
          home:
            type: string
            default: $HOME
          bindings:
            type: list
            schema:
              type: string
          gpu:
            type: boolean
            default: False
      jupyter:
        type: dict
        required: False
        schema:
          flavor:
            type: string
            required: False
            allowed:
              - notebook
              - lab
              - R
            default: notebook
          port:
            type: integer
            required: True
