# Automated package testing

name: Test code
on:
  push:
    branches-ignore:
      - staging
      - main

jobs:
  test:
    name: Test package code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - name: Setup Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install required packages
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install --upgrade setuptools
          python3 -m pip install --upgrade -r requirements/testing.txt

      - name: Test codebase
        run: |
          python3 -m pytest 2>&1 | tee testing.log

      - name: Upload logs
        uses: actions/upload-artifact@v2
        with:
          name: Testing
          path: testing.log

      - name: Interrupt workflow if tests failed
        run: |
          if grep -q FAILED testing.log; then exit 125; fi
